enum AppEvents {
    FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS",
    FORM_SUBMIT_FAIL = "FORM_SUBMIT_FAIL",
    DELETE_HISTORY_ITEM = "DELETE_HISTORY_ITEM",
    OPEN_DIALOG = "OPEN_DIALOG",
    CLOSE_DIALOG = "CLOSE_DIALOG"
}

export default AppEvents;
